name: autoformsai_blogs
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg:
  flutter_quill: ^10.8.5
  flutter_markdown: ^0.7.5
  provider: ^6.1.2
  flutter_widget_from_html: ^0.15.3
  vsc_quill_delta_to_html: ^1.0.5
  image_picker: ^1.1.2
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  timeago: ^3.7.0
  another_easyloading:
    git: https://github.com/subhashDev11/another_easyloading.git
  get_it: ^8.0.3
  logger: ^2.5.0
  equatable: ^2.0.7
  dynamic_path_url_strategy: ^1.0.0
  url_launcher: ^6.3.1
  flutter_bloc: ^9.0.0
  go_router: ^14.6.3
  flutter_tts: ^4.2.1
  flutter_html: ^3.0.0-beta.2
  font_awesome_flutter: ^10.8.0
  http: ^1.2.2
  photo_view: ^0.15.0
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/dummy.svg
     - assets/image_icon.png
     - assets/profile_img.jpeg
     - assets/speaking.png


